In [1]:
%matplotlib inline
import numpy as np
import sklearn as skl
import matplotlib.pyplot as plt

In [2]:
train_path = 'mnist'
test_path = 'mnist.t'
data_dim = 784

def reader(path):
    data_img = []
    data_label = []
    with open(str(path),'r') as FP:
        for line in FP:
            segment = line.split(' ')
            label = segment[0]
            img = np.zeros(data_dim, dtype=np.float32)
            for v in segment[1:]:
                index, value = v.split(':')
                img[int(index)] = float(value) / 255.
            data_img.append(img)
            data_label.append(label)
    return np.array(data_img), np.array(data_label)



In [3]:
training_img, training_label = reader(train_path)
testing_img, testing_label = reader(test_path)
print len(training_img)
print len(testing_img)

60000
10000


In [4]:
from sklearn.decomposition import PCA
pca = PCA(n_components=20)
reduced_train_img = pca.fit_transform(training_img)
print 'Information left: ', np.sum(pca.explained_variance_ratio_)

Information left:  0.643581


In [5]:
from sklearn.svm import SVC
clf = SVC(verbose=True)
%time clf.fit(reduced_train_img, training_label)


[LibSVM]CPU times: user 29.1 s, sys: 292 ms, total: 29.3 s
Wall time: 29.6 s


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=True)

In [6]:
mean_score_on_testing_set = clf.score(pca.transform(testing_img), testing_label)
print 'score on testing set:', mean_score_on_testing_set

score on testing set: 0.9801


In [7]:
predicted = clf.predict(pca.transform(testing_img))
confusion_metrix = skl.metrics.confusion_matrix(testing_label, predicted)
print confusion_metrix
inclass_precision = skl.metrics.classification_report(testing_label, predicted)
print inclass_precision

[[ 972    0    1    1    0    2    2    1    1    0]
 [   0 1129    2    2    0    0    0    0    1    1]
 [   2    0 1014    2    1    1    0    8    4    0]
 [   0    0    2  996    0    3    0    6    2    1]
 [   0    0    2    0  961    0    2    0    1   16]
 [   2    0    0   10    1  870    2    1    5    1]
 [   5    3    1    0    4    2  941    0    2    0]
 [   0    4    9    0    2    0    0 1000    1   12]
 [   2    0    2    4    4    4    1    2  953    2]
 [   2    5    0    5   15    3    1   10    3  965]]
             precision    recall  f1-score   support

          0       0.99      0.99      0.99       980
          1       0.99      0.99      0.99      1135
          2       0.98      0.98      0.98      1032
          3       0.98      0.99      0.98      1010
          4       0.97      0.98      0.98       982
          5       0.98      0.98      0.98       892
          6       0.99      0.98      0.99       958
          7       0.97      0.97      0.97  